global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9200"]

  # Scrape cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]
scrape_configs:
  - job_name: "ai-artistic-style-service"
    static_configs:
      - targets: ["ai-artistic-style-service:5001"]
