name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nehatanuj      # Replace with your Docker Hub username
          password: dckr_pat_0R_OuLD_slmRBvoCa4Vvmc8eZuA     # Replace with your Docker Hub password or access token

      - name: Build and push Docker image
        run: |
          docker build -t nehatanuj/ai-visual-crafts:latest .
          docker push nehatanuj/ai-visual-crafts:latest

