name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx (optional but recommended for building multi-architecture images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t nehatanuj:latest .

    - name: Push the Docker image
      run: docker push nehatanuj:latest
    # Optional: Run tests (if any)
    - name: Run tests
      run: |
        # Add your test command here (e.g., `npm test` or `pytest`)
        echo "Running tests"

    # Optional: Deploy the application (if any deployment step is needed)
    - name: Deploy application
      run: |
        # Add your deployment command here
        echo "Deploying to server"

